// Seed curado por el equipo (no crowdsourced). Mantener todo en MAYÚSCULAS sin tildes,
// porque normalizeName las aplica antes de buscar.
export const ABBREVIATIONS: Readonly<Record<string, string>> = {
  LCH: "LECHE",
  DESLAC: "DESLACTOSADA",
  DESLACT: "DESLACTOSADA",
  ACEIT: "ACEITE",
  AZUC: "AZUCAR",
  ARRZ: "ARROZ",
  FRJL: "FRIJOL",
  HUEV: "HUEVOS",
  JABN: "JABON",
  JBN: "JABON",
  PAPL: "PAPEL",
  HIGN: "HIGIENICO",
  CHCL: "CHOCOLATE",
  GAS: "GASEOSA",
  AGU: "AGUA",
  QUES: "QUESO",
  MANT: "MANTEQUILLA",
  YOGT: "YOGURT",
  HARN: "HARINA",
  PIM: "PIMIENTA",
  DET: "DETERGENTE",
  SHAMP: "SHAMPOO",
  GALL: "GALLETAS",
  PASTA: "PASTA",
  TOM: "TOMATE",
};
