/// <reference types="expo/types" />

// NOTE: This file should not be edited. It is generated by Expo and kept in
// version control so `tsc` (and CI) have Expo's ambient types without first
// running the dev server.
